baseurl = "http://www.lowrisc.org/"
languageCode = "en-us"
title = "lowRISC"

[permalinks]
blog="/blog/:year/:month/:slug"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "FAQ"
    identifier = "FAQ"
    url = "/faq/"
    weight = 3

[[menu.main]]
    name = "Docs"
    identifier = "docs"
    url = "/docs/"
    weight = 4

[[menu.main]]
    name = "Community"
    identifier = "community"
    url = "/community/"
    weight = 5
